name: penjualan
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.2+12

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.4
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  flutter_form_builder: ^6.1.0+1
  get_storage: ^2.0.3
  crypto: ^3.0.1
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^9.2.0
  expandable: ^5.0.1
  debounce_throttle: ^2.0.0
  flutter_multi_formatter: ^2.5.1
  syncfusion_flutter_xlsio: ^19.3.59-beta
  open_file: ^3.2.1
  printing: ^5.7.3
  external_path: ^1.0.1
  permission_handler: ^9.2.0
  file_picker: ^4.5.1
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.2
  flutter_custom_dialog: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/img/cod-android.png"
  image_path_ios: "assets/img/cod-ios.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/img/cod-android.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/img/
    - assets/img/FinalLogo.png
    - assets/img/cod-android.png
    - assets/img/cod-ios.png

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial/arial.ttf
